apiVersion: gitops.eksctl.io/v1alpha1
kind: Cluster
metadata:
  revision: 2
spec:
  state: present
  timeout: 40m
  template:
    apiVersion: eksctl.io/v1alpha5
    kind: ClusterConfig
    metadata:
      name: new-fargate
      region: us-west-2
      version: "1.16"
    nodeGroups:
    - name: ng-1
      instanceType: m5.xlarge
      desiredCapacity: 1
      volumeSize: 120
    fargateProfiles:
    - name: fp-default
      selectors:
      - namespace: default
      - namespace: application
  profiles: []
